#!/usr/bin/env bash

set -e

dir="${BASH_SOURCE%/*}"

source "$dir/../definitions"

for i in {0..2}; do
    vm_name="control$i"
    vm_id=$(get_vm_id "$vm_name")

    echo "$dir"
    scp \
        -i "$(get_ssh_key_path)" \
        "$dir/ca.pem" \
        "$dir/ca-key.pem" \
        "$dir/kubernetes-key.pem" \
        "$dir/kubernetes.pem" \
        "$dir/service-account-key.pem" \
        "$dir/service-account.pem" \
        "$dir/admin.kubeconfig" \
        "$dir/kube-controller-manager.kubeconfig" \
        "$dir/kube-scheduler.kubeconfig" \
        "$dir/encryption-config.yaml" \
        "$dir/$vm_name.pem" \
        "$dir/$vm_name-key.pem" \
        "$dir/$vm_name.kubeconfig" \
        "$dir/kube-proxy.kubeconfig" \
        ubuntu@"$(get_inet "$vm_id")":~
done

for i in {0..2}; do
    vm_name="worker$i"
    vm_id=$(get_vm_id "$vm_name")

    echo "$dir"
    scp \
        -i "$(get_ssh_key_path)" \
        "$dir/ca.pem" \
        "$dir/$vm_name.pem" \
        "$dir/$vm_name-key.pem" \
        "$dir/$vm_name.kubeconfig" \
        "$dir/kube-proxy.kubeconfig" \
        ubuntu@"$(get_inet "$vm_id")":~
done
