#!/usr/bin/env bash

arch=arm64
k8s_version=1.31.4

get_vm_name() {
    id="$1"
    if [[ ! $id =~ ^-?[0-9]+$ ]]; then
        echo "Bad machine ID: $id" >&2
        return 1
    elif [[ $id -eq 0 ]]; then
        echo gateway
    elif [[ $id -le 3 ]]; then
        echo control$((id-1))
    elif [[ $id -le 6 ]]; then
        echo worker$((id-4))
    fi
}

get_vm_id() {
    vm_name="$1"
    names=(gateway control{0..2} worker{0..2})

    for i in "${!names[@]}"; do
        if [[ "${names[$i]}" = "$vm_name" ]];then
            echo "$i"
        fi
    done
}

inet_nw_bits=192.168.200

get_inets() {
    inets=()
    for ((i=0;i<7;i++))
    do
        inets[i]=$inet_nw_bits.$((i+3))
    done

    echo "${inets[*]}"
}

get_inet() {
    vm_id="$1"

    echo "$inet_nw_bits.$((vm_id+3))"
}

get_ssh_key_path() {
    local dir="${BASH_SOURCE%/*}"
    echo "$dir/vms/vm-ssh-key"
}
