#!/usr/bin/env bash

export arch=arm64

# Base network definitions.
export kubenet_nw_bits=192.168.200
export kubenet_if_inet=$kubenet_nw_bits.1
export kube_api_inet=192.168.200.11

# Versions for installed components.
export etcd_version=3.5.17
export k8s_version=1.31.4
export containerd_version=2.0.2
export cni_spec_version=1.0.1
export cri_version=1.32.0
export runc_version=1.2.4

get_vm_name() {
    id="$1"
    if [[ ! $id =~ ^-?[0-9]+$ ]]; then
        echo "Bad machine ID: $id" >&2
        return 1
    elif [[ $id -eq 0 ]]; then
        echo gateway
    elif [[ $id -le 3 ]]; then
        echo control$((id-1))
    elif [[ $id -le 6 ]]; then
        echo worker$((id-4))
    fi
}

get_vm_id() {
    vm_name="$1"
    names=(gateway control{0..2} worker{0..2})

    for i in "${!names[@]}"; do
        if [[ "${names[$i]}" = "$vm_name" ]];then
            echo "$i"
        fi
    done
}

get_inets() {
    inets=()
    for ((i=0;i<7;i++))
    do
        inets[i]=$kubenet_nw_bits.$((i+3))
    done

    echo "${inets[*]}"
}

get_inet() {
    vm_id="$1"
    echo "$kubenet_nw_bits.$((vm_id+3))"
}

get_ssh_key_path() {
    local dir="${BASH_SOURCE%/*}"
    echo "$dir/vms/vm-ssh-key"
}
