#!/usr/bin/env bash

set -e

if [[ "$EUID" -ne 0 ]]; then
    echo "setup: the script must be run as root" >&2
    exit 1
fi

while [[ ! -f /etc/ha.d/ldirectord.cf ]]; do
    echo "setup: waiting for ldirectord to be installed..."
    sleep 1
done

cat <<EOF | tee /etc/ha.d/ldirectord.cf
checktimeout=5
checkinternal=1
autoreload=yes
quiescent=yes

virtual=192.168.200.11:6443
    servicename=kube-api
    real=192.168.200.4:6443 gate
    real=192.168.200.5:6443 gate
    real=192.168.200.6:6443 gate
    scheduler=wrr
    checktype=negotiate
    service=https
    request="healthz"
    receive="ok"
EOF

systemctl restart ldirectord
