#!/usr/bin/env bash

set -e

dir=${BASH_SOURCE%/*}

source "$dir/../definitions"

kubectl config set-cluster kubenet \
    --certificate-authority="$dir/ca.pem" \
    --embed-certs=true \
    --server=https://$kube_api_inet:6443

kubectl config set-credentials admin \
    --client-certificate="$dir/admin.pem" \
    --client-key="$dir/admin-key.pem" \
    --embed-certs=true

kubectl config set-context kubenet \
    --cluster=kubenet \
    --user=admin

kubectl config use-context kubenet
