#!/usr/bin/env bash

get_vm_name() {
    id="$1"
    if [[ ! $id =~ ^-?[0-9]+$ ]]; then 
        echo "Bad machine ID: $id" >&2
        return 1
    elif [[ $id -eq 0 ]]; then
        echo gateway
    elif [[ $id -le 3 ]]; then
        echo control$((id-1))
    elif [[ $id -le 6 ]]; then
        echo worker$((id-4))
    fi
}

get_inets() {
    inets=()
    for ((i=0;i<7;i++))
    do
        inets[i]=192.168.200.$((i+3))
    done

    echo "${inets[*]}"
}
