#!/usr/bin/env bash

get_vm_name() {
    id="$1"
    if [[ ! $id =~ ^-?[0-9]+$ ]]; then 
        echo "Bad machine ID: $id" >&2
        return 1
    elif [[ $id -eq 0 ]]; then
        echo gateway
    elif [[ $id -le 3 ]]; then
        echo control$((id-1))
    elif [[ $id -le 6 ]]; then
        echo worker$((id-4))
    fi
}

inet_nw_bits=192.168.200

get_inets() {
    inets=()
    for ((i=0;i<7;i++))
    do
        inets[i]=$inet_nw_bits.$((i+3))
    done

    echo "${inets[*]}"
}

get_ssh_cmd() {
    vm_id="$1"

    dir=$(dirname "$0")
    echo "ssh ubuntu@$inet_nw_bits.$((vm_id+3)) -i $dir/vm-ssh-key"
}
