#!/usr/bin/env bash

set -e

dir=${BASH_SOURCE%/*}

vm_inet="$1"

until nc -zw 10 "$vm_inet" 22; do sleep 1; done

# Remove the stale entries for a given VM.
if [[ -f "$HOME/.ssh/known_hosts" ]]; then
    sed -i '' "/^$vm_inet/d" "$HOME/.ssh/known_hosts"
fi

ssh-keyscan "$vm_inet" 2> /dev/null >> "$HOME/.ssh/known_hosts"

until ssh "ubuntu@$vm_inet" -i "$dir/vm-ssh-key" exit; do sleep 1; done
