#!/usr/bin/env bash

kube_api_inet="$1"

if ! helm list | grep -q "cilium"; then
    helm repo add cilium https://helm.cilium.io/
fi

if ! kubectl get pods -n kube-system | grep -q "cilium"; then
    helm install -n kube-system cilium cilium/cilium \
        --set kubeProxyReplacement=true \
        --set k8sServiceHost="$kube_api_inet" \
        --set k8sServicePort=6443 \
        --set cgroup.automount.enabled=false \
        --set cgroup.hostRoot=/sys/fs/cgroup \
        --wait --timeout 15m
fi
